// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrk5MrMG2OoUxMUXBGbCy-YXxJsZUHJko',
    appId: '1:322542231420:web:02ae861730eafb1f65cef9',
    messagingSenderId: '322542231420',
    projectId: 'nj-pizza-delivery',
    authDomain: 'nj-pizza-delivery.firebaseapp.com',
    storageBucket: 'nj-pizza-delivery.firebasestorage.app',
    measurementId: 'G-8QKTE437ZG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-14DDDXgWjCNk7agwM2mma0G0GTPqHvY',
    appId: '1:322542231420:android:66d1518429806b9e65cef9',
    messagingSenderId: '322542231420',
    projectId: 'nj-pizza-delivery',
    storageBucket: 'nj-pizza-delivery.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfFjBB7sYaTmLwNHUocuhBaIC7sdsi7II',
    appId: '1:322542231420:ios:7d8fdbbb1f4d5df665cef9',
    messagingSenderId: '322542231420',
    projectId: 'nj-pizza-delivery',
    storageBucket: 'nj-pizza-delivery.firebasestorage.app',
    iosBundleId: 'com.example.njPizzaDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfFjBB7sYaTmLwNHUocuhBaIC7sdsi7II',
    appId: '1:322542231420:ios:7d8fdbbb1f4d5df665cef9',
    messagingSenderId: '322542231420',
    projectId: 'nj-pizza-delivery',
    storageBucket: 'nj-pizza-delivery.firebasestorage.app',
    iosBundleId: 'com.example.njPizzaDelivery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrk5MrMG2OoUxMUXBGbCy-YXxJsZUHJko',
    appId: '1:322542231420:web:f9650204483aba6265cef9',
    messagingSenderId: '322542231420',
    projectId: 'nj-pizza-delivery',
    authDomain: 'nj-pizza-delivery.firebaseapp.com',
    storageBucket: 'nj-pizza-delivery.firebasestorage.app',
    measurementId: 'G-FYT02KJ4FE',
  );
}
